### ISSUE TITLE
how is trangeview to pointview implemented

### ISSUE THREAD

**Issue by rXYZkit** [sanjeev-sudarsan/Rangercnn#1]
Hi, in which part of the rangeview to pointview is implemented, I see that it directly converts the rangenet dedaode rangeview features to bev features?

**Comment by sanjeev-sudarsan** [comment]
The rangeimage `batch_dict['rangemap_xyz']`  has the 3d coordinates of the point cloud. Therfore it can be reshaped back into a point cloud. We can then use the indices of this point cloud to reproject `batch_dict['range_res']` into a point cloud. 

This is done in this [file](https://github.com/sanjeev-sudarsan/Rangercnn/blob/master/pcdet/models/range_base/rv2bev/rang2bev.py)
